### ISSUE TITLE
No sdist on PyPI, and no release tag on GitHub

### ISSUE THREAD

**Issue by hoechenberger** [drbenvincent/darc_toolbox#84]
Hello, currently there is no source distribution (`sdist`) on PyPI. Could you please upload the sdist? (you can create it via `python setup.py sdist`; you need to add a `MANIFEST.in` file to ensure the license file is packaged along the source code).

Also, since there's currently no release tags on the GitHub repository, it's not possible to reliably figure out which revision of the code one is actually retrieving / running. Do you think you could add tags, at least for future releases?

Thank you!

**Comment by drbenvincent** [comment]
Sure. Will certainly add tagged Github releases for future versions.

This is my first encounter with PyPI so I'm still learning. Will give it a go, but might have to ask if I get really stuck.

**Comment by hoechenberger** [comment]
No problem, thank you!  I can also give you more detailed instructions if desired :)

**Comment by drbenvincent** [comment]
Maybe I do need some help here. Previous I was using

    python setup.py bdist_wheel
    twine upload dist/nameOfPackage.whl

So is it as simple as adding the sdist to the first line? 

    python setup.py bdist_wheel sdist

Presumably I need to change what I am uploading also with the second line? Could you just clarify what I'd need to do there please?

PS. I saw some advice saying that you can include the licence file just by adding `data_files = [("", ["LICENSE"])]` into your `setup.py` file. So I'll opt for that as it seems like the simplest/smallest change.

**Comment by hoechenberger** [comment]
The python setup.py bdist_wheel sdist will create both a .whl and a .zip or .tar.gz file (depending on your OS) in the dist directory. You need to pass those filenames to twine to upload them. 

The proper way to include additional files like the license in the sdist is to create a MANIFEST.in with contents like:

include LICENSE
include README.txt

And to add include_package_data=True to the call to setup(). Anything else won’t work reliably or only for other “destinations” than sdist. 

Hope that helps


--

**Comment by hoechenberger** [comment]
For reference, see https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files

**Comment by drbenvincent** [comment]
Most of this is done. Will do the rest via #86
