### ISSUE TITLE
Source code of dependency "badapted" not available

### ISSUE THREAD

**Issue by hoechenberger** [drbenvincent/darc_toolbox#85]
Hello,  since only a binary wheel of the dependency `badapted` is provided on PyPI, I followed the "Homepage" link from the package description, which points to https://github.com/drbenvincent/badapted

However, this repository does not exist. Where can I find the sources of `badapted`?

Thanks!

**Comment by drbenvincent** [comment]
I accidentally left this as a private repo. Will make it public now.

**Comment by hoechenberger** [comment]
Awesome, thanks so much!
